services:
  api-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treblle-api-monitor
    ports:
      - "8080:8080"
    environment:
      # Set Gin to release mode for production
      - GIN_MODE=release
      # Configure database path to use persistent volume
      - DB_PATH=/app/data/api_monitor.db
      # Set timezone
      - TZ=UTC
    volumes:
      # Persist the SQLite database on host machine
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - api-monitor-network

networks:
  api-monitor-network:
    driver: bridge

